name: Test and Build

on:
  pull_request:

jobs:
  testing:
    name: Test and Build the bootstrap
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go-version:
          - '1.22'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Show Go version
        run: go version

      - name: Test and Build the bootstrap
        run: |
          go install golang.org/x/tools/cmd/stringer@latest

          make -C bootstrap test
          make -C bootstrap build
      - name: build the examples
        run: |
          bootstrap/bin/zergb -vv docs/examples/simple/00-hello-world.zg
